# HRDT RobotWin Training Configuration with Embodiment-Aware Action Encoder (DINOv2, 224px)
latent_motion_tokenizer_config_path: "/dataset_rc_mm/chenby10@xiaopeng.com/Moto_copy/latent_motion_tokenizer/configs/models/robotwin_action_only_dct_transformer.yaml"
dataset_config_path: "/dataset_rc_mm/chenby10@xiaopeng.com/Moto_copy/latent_motion_tokenizer/configs/data/hrdt_robotwin.yaml"

dataloader_config:
  bs_per_gpu: 64
  workers_per_gpu: 16
  prefetch_factor: 2

rgb_preprocessor_config:
  model_vision_type: "dino"
  vision_aug_config:
    do_random_resized_crop: false
    do_random_shift: true

training_config:
  num_epochs: 10
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 1
  save_epochs: 2
  save_steps: 5000
  save_path: "/dataset_rc_mm/chenby10@xiaopeng.com/Moto_copy/latent_motion_tokenizer/outputs/action_only_dct_transformer/"
  resume_ckpt_path: null

# Embodiment-aware trainer settings (training-time drop)
embodiment_trainer_config:
  action_drop_prob: 0.0
  vision_drop_prob: 1.0


