# HRDT RobotWin Training Configuration with DINOv2 (224px)
latent_motion_tokenizer_config_path: "/dataset_rc_mm/chenby10@xiaopeng.com/Moto_copy/latent_motion_tokenizer/configs/models/vq_size128_dim32_num8_legacyTrue-vision_DinoV2Large-decoder_queryFusionModeAdd_Patch196_useMaskFalse-mformer_legacyTrue.yaml"
dataset_config_path: "/dataset_rc_mm/chenby10@xiaopeng.com/Moto_copy/latent_motion_tokenizer/configs/data/hrdt_robotwin.yaml"

dataloader_config:
  bs_per_gpu: 8  # Batch size per GPU
  workers_per_gpu: 4
  prefetch_factor: 2

rgb_preprocessor_config: 
  model_vision_type: "dino"  # Changed from "mae" to "dino"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true

training_config:
  num_epochs: 10
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 2
  save_epochs: 2
  save_steps: 5000
  save_path: "/dataset_rc_mm/chenby10@xiaopeng.com/Moto_copy/latent_motion_tokenizer/outputs/hrdt_robotwin_dinov2_trained/"
  resume_ckpt_path: null
